### ISSUE TITLE
 Is version 3.14 the latest version available for Windows 7?

### ISSUE THREAD

**Issue by DOSforever** [ar51an/iperf3-win-builds#8]
or 3.13?

**Comment by ar51an** [comment]
Isn't the latest `3.17.1` work on Win7 64Bit?

**Comment by ar51an** [comment]
Is it Win7 64Bit?
Isn't the latest 3.17.1 work on Win7 64Bit?
BTW the EOL for Win7 was January 14th, 2020. I never tested or compiled any version on Win7.

**Comment by DOSforever** [comment]
Yes, Windows 7 64-bit. When I run 3.17.1 it pops up a prompt box:

>\---------------------------
iperf3.exe - Unable to find entrance
\---------------------------
Unable to locate program input point GetSystemTimePreciseAsFileTime on dynamic link library KERNEL32.dll. 
\---------------------------
OK
\---------------------------

I later tested 3.14 would work under Windows 7.

**Comment by ar51an** [comment]
The function `GetSystemTimePreciseAsFileTime` was added in Kernel32.dll in Windows 8 and onwards. So the latest version of iperf3 will work on Windows 8 and onwards.

I compiled the iperf3 newest version 3.17.1 executable for Win7 64Bit by changing the win version build variables. Try it out and let me know if it works on Win7:
~~iperf-3.17.1-win7-64Bit.zip~~

I do not have Win7 VM available right now to test the above version on Win7 and to create a dedicated version for Win7. If it works on Win7 you are good. Microsoft marked Win7 end of line on Jan 14th, 2020. So do not expect future versions of iperf3 for Win7. If it does not work then use the iperf3 version 3.14, as you mentioned above that works on Win7.

*Edit: Removed iperf3 executable, it did not work on Windows 7.

**Comment by DOSforever** [comment]
非常感谢你为 Win7 专门做了一次编译，我试了下，依然不能做最基本的运行，如 iperf3.exe 不带任何选项 ，仍然出现上述出错提示框。
原本我只想知道下最晚适合某个 Windows 版本有哪些，如果作者能有机会能推出适合各个 Windows 版的最好，没有的话也就算了，但最好能说明下适合 Windows 的版本。谢谢。

---

Thank you very much for making a special compilation for Win7, I've tried it and it still doesn't do the most basic things, such as iperf3.exe without any options, and still shows the error box mentioned above.
I would like to know what the latest version for Windows is, if the author has the ability to release a version for each version of Windows that would be great, if not that's fine but it would be good to have a description of the version for Windows. Thank you very much.

**Comment by DOSforever** [comment]
Tested 3.16 is the last version to run under Windows 7, with only the most basic running tests, such as without any options and with --version, --help options and basic througthput test.

**Comment by ar51an** [comment]
> Tested 3.16 is the last version to run under Windows 7

Thank you. This was helpful in figuring out why the latest version of iperf3 is not working on Windows 7. Cygwin dropped the support for Windows 7 from version 3.5.0 onwards.

![cygwin-release-notes](https://github.com/user-attachments/assets/f11f554e-465c-4b61-805f-ccd72cc4c514)

I have pulled the old Cygwin version 3.4.10 to compile iperf3 newest version 3.17.1 executable for Windows 7 64Bit.

[iperf-3.17.1-win7-64Bit.zip](https://github.com/user-attachments/files/17514854/iperf-3.17.1-win7-64Bit.zip)

|iperf Ver    |Cygwin Ver      |OS          |
|:-----------:|:--------------:|:----------:|
|3.17.1       |3.4.10-1.x86_64 |Win7 64-bit |

Please do test it out and let me know if it works on Windows 7. It will be helpful for future iperf3 Windows 7 releases. Again I do not have Windows 7 virtual machine available so I cannot validate it.

**Comment by DOSforever** [comment]
> I have pulled the old Cygwin version 3.4.10 to compile iperf3 newest version 3.17.1 executable for Windows 7 64Bit.
> 
> [iperf-3.17.1-win7-64Bit.zip](https://github.com/user-attachments/files/17514854/iperf-3.17.1-win7-64Bit.zip)
> 
> iperf Ver	Cygwin Ver	OS
> 3.17.1	3.4.10-1.x86_64	Win7 64-bit
> Please do test it out and let me know if it works on Windows 7. It will be helpful for future iperf3 Windows 7 releases. Again I do not have Windows 7 virtual machine available so I cannot validate it.

Thank you very much. It works. Of course, I only ran the most basic and simple tests, such as the --version, --help, -s, -c, -R, -f, -P, --bidir options, and there were no errors.
