### ISSUE TITLE
win7无法使用

### ISSUE THREAD

**Issue by workmengxue** [ar51an/iperf3-win-builds#9]
![image](https://github.com/user-attachments/assets/ea3512c0-ec5a-4621-942d-3aef70908bef)

**Comment by ar51an** [comment]
EOL for Win7 was Jan 14th, 2020. I never tested or compiled any version on Win7.
Are you trying to run it on 32Bit Win7?

**Comment by workmengxue** [comment]
我的win7是64位的 T_T

**Comment by ar51an** [comment]
Check the issue https://github.com/ar51an/iperf3-win-builds/issues/8
